version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "react",
    "vue"
  ]
  environment = ["nodejs"]

[[code_formatters]]
name = "prettier"

[[code_formatters]]
name = "standardjs"